#!/bin/sh

DAYSTOKEEP=30
BUCKET=$(hostname)
PREFIX="backups"

# -------------

abort() {
	echo $@
	exit 1
}

date2epoch() {
	date -d "$@" +%s
}

date2sort() {
	date -d "$@" +%F
}


EXPIRES=$(($DAYSTOKEEP * 86400))
EXPIRE_TIME=$(( $(date2epoch now) - $EXPIRES ))

# ---- main ----

[ -z "$BUCKET" ] && abort "specify BUCKET name"
[ -z "$PREFIX" ] && abort "specify PREFIX"
[ -z "$EXPIRES" ] && abort "specify DAYSTOKEEP/fix EXPIRES"

#	get the list of daily backups
BACKUPS=$(/usr/bin/yes | s3cmd list "$BUCKET:$PREFIX" | grep -v 'More? Y/n' | grep -v -- '--------------------' | cut -d/ -f 2 | sort -u )

#	clear old backups
for DATE in $BACKUPS; do
	[ $(date2epoch $DATE) -lt $EXPIRE_TIME ]   &&    s3cmd deleteall "$BUCKET:$PREFIX/$DATE"
done

#	backup current stuff
NOW=$(date2sort now)
TMPDIR=$(mktemp -d)

tar -C /var -zcf "${TMPDIR}/mail-$NOW.tgz" mail/
s3sync -r "${TMPDIR}/" "$BUCKET:$PREFIX/$NOW/" 
s3sync -r /var/backups/mysql/latest/ "$BUCKET:$PREFIX/$NOW/" 
rm -rf ${TMPDIR}

