#!/bin/sh

DAYSTOKEEP=30
BUCKET=$(hostname)
PREFIX="backups"
S3SYNC="/var/lib/gems/1.8/bin/s3sync"
S3CMD="/var/lib/gems/1.8/bin/s3cmd"

# -------------

abort() {
	echo $@
	exit 1
}

date2epoch() {
	date -d "$@" +%s
}

date2sort() {
	date -d "$@" +%F
}


EXPIRES=$(($DAYSTOKEEP * 86400))
EXPIRE_TIME=$(( $(date2epoch now) - $EXPIRES ))

# ---- main ----

[ -z "$BUCKET" ] && abort "specify BUCKET name"
[ -z "$PREFIX" ] && abort "specify PREFIX"
[ -z "$EXPIRES" ] && abort "specify DAYSTOKEEP/fix EXPIRES"

#	get the list of daily backups
BACKUPS=$(/usr/bin/yes | $S3CMD list "$BUCKET:$PREFIX" | grep "^$PREFIX/" | cut -d/ -f 2 | sort -u )

#	clear old backups
for DATE in $BACKUPS; do
	[ $(date2epoch $DATE) -lt $EXPIRE_TIME ]   &&    $S3CMD deleteall "$BUCKET:$PREFIX/$DATE"
done

#	backup current stuff
NOW=$(date2sort now)
TMPDIR=$(mktemp -d)

tar -C /var -zcf "${TMPDIR}/mail-$NOW.tgz" mail/
$S3SYNC -r "${TMPDIR}/" "$BUCKET:$PREFIX/$NOW/" 
$S3SYNC -r /var/backups/mysql/latest/ "$BUCKET:$PREFIX/$NOW/" 
rm -rf ${TMPDIR}

